CREATE DATABASE UNIVERSIDADE;
USE UNIVERSIDADE;

/*ALUNO*/
CREATE TABLE IF NOT EXISTS ALUNO(
	id_aluno INT AUTO_INCREMENT PRIMARY KEY,
    matricula VARCHAR(50) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    endereço VARCHAR(50) NOT NULL,
    cidade VARCHAR(50) NOT NULL
);

INSERT INTO ALUNO (matricula,nome, endereço, cidade)
VALUES
	('2015010101', 'JOSE DE ALENCAR', 'RUA DAS ALMAS', 'NATAL'),
	('2015010102', 'JOÃO JOSÉ', 'AVENIDA RUY CARNEIRO', 'JOÃO PESSOA'),
	('2015010103', 'MARIA JOAQUINA', 'RUA CARROSSEL', 'RECIFE'),
	('2015010104', 'MARIA DAS DORES', 'RUA DAS LADEIRAS', 'FORTALEZA'),
	('2015010105', 'JOSUÉ CLAUDINO DOS SANTOS', 'CENTRO', 'NATAL'),
	('2015010106', 'JOSUÉLISSON CLAUDINO DOS SANTOS', 'CENTRO', 'NATAL');
    
SELECT * FROM ALUNO;

/*DISCIPLINA*/
CREATE TABLE IF NOT EXISTS DISCIPLINA(
	id_disciplina INT AUTO_INCREMENT PRIMARY KEY,
    cod_disc VARCHAR(50) NOT NULL,
    nome_disc VARCHAR(50) NOT NULL,
    carga_hor INT NOT NULL
);

INSERT INTO DISCIPLINA (cod_disc,nome_disc,carga_hor)
VALUES
	('BD', 'BANCO DE DADOS', '100'),
	('POO', 'PROGRAMAÇÃO COM ACESSO A BANCO DE DADOS', '100'),
	('WEB', 'AUTORIA WEB', '50'),
	('ENG', 'ENGENHARIA DE SOFTWARE', '80');

SELECT * FROM DISCIPLINA;


/*PROFESSORES*/
CREATE TABLE IF NOT EXISTS PROFESSORES(
	id_professores INT AUTO_INCREMENT PRIMARY KEY,
    cod_disc VARCHAR(50) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    endereço VARCHAR(50) NOT NULL,
    cidade VARCHAR(50) NOT NULL
);

INSERT INTO PROFESSORES (cod_disc,nome,endereço,cidade)
VALUES
	('212131', 'NICKERSON FERREIRA', 'RUA MANAÍRA', 'JOÃO PESSOA'),
	('122135', 'ADORILSON BEZERRA', 'AVENIDA SALGADO FILHO', 'NATAL'),
	('192011', 'DIEGO OLIVEIRA', 'AVENIDA ROBERTO FREIRE', 'NATAL');
    
SELECT * FROM PROFESSORES;

/*TURMA*/
CREATE TABLE IF NOT EXISTS TURMA(
	id_turma INT AUTO_INCREMENT PRIMARY KEY,
    cod_disc VARCHAR(50) NOT NULL,
    cod_turma VARCHAR(50) NOT NULL,
    cod_prof VARCHAR(50) NOT NULL,
    ano INT NOT NULL,
	horario VARCHAR(50) NOT NULL
);

INSERT INTO TURMA (cod_disc, cod_turma, cod_turma, cod_prof, ano, horario )
VALUES
	('BD', '1,212131', '2015', '11H-12H'),
    ('BD', '2', '212131', '2015', '13H-14H'),
    ('POO', '1', '192011', '2015', '08H-09H'),
    ('WEB', '1', '192011', '2015', '07H-08H'),
    ('ENG', '1', '122135', '2015', '10H-11H');
    
SELECT * FROM TURMA;

/*HISTORICO*/
CREATE TABLE IF NOT EXISTS HISTORICO(
	id_historico INT AUTO_INCREMENT PRIMARY KEY,
    matricula VARCHAR(50) NOT NULL,
    cod_disc VARCHAR(50) NOT NULL,
    cod_turma VARCHAR(50) NOT NULL,
    cod_prof VARCHAR(50) NOT NULL,
	ano INT NOT NULL,
    frequencia VARCHAR(50) NOT NULL,
    nota INT NOT NULL
);

INSERT INTO HISTORICO (matricula, cod_disc,cod_turma, cod_prof, ano, frequencia, nota)
VALUES
	('DAE6534', 'Ford', 'Fiesta', 1999),
    ('DKL4598', 'Wolksvagen', 'Gol' , 2001),
    ('DKL7878', 'Ford', 'Fiesta', 2001);
    
SELECT * FROM HISTORICO;
